### PR TITLE
added html solution to the player

### PR DESCRIPTION
**Pull request by ottonascarella**
The "solution" option of the player should contain both html and aurora.
This way we can profit from native mp3, wav, webm and ogg capabilities from the browsers.
Mp3 are playing normal now. But AIFF does not seem to work: I could not find in aurora's documentation support for it. I reckon we'll have to build it.

### CODE REVIEW

**Comment by danryu** [comment]
Cool, you've caught up already....

Yes specifying solution "html" should use good-old HTML5 native audio handling. Which if you check the spec does not include AIFF.

To compare, I made a branch "nonaurora" which basically specifies just HTML and forgets aurora. 

So the last thing I tested - the master branch -using aurora - actually PLAYED 16-bit AIFF files ... but not 24-bit AIFF. And didn't play mp3s either.

**Comment by ottonascarella** [comment]
Cool
Can you share the audio files you've been testing the app against with me?
It should be good to have same file converted in all the types we want to
support...let me produce those for us.
Also, it'd be amazing if you could add to your Google Console
http://localhost:8080 alone (without the "/index.html")

**Comment by danryu** [comment]
Ok

I made a GDrive directory with a few of the files I've been testing with ...
You should have permission to view and edit:
https://drive.google.com/open?id=0B_TTqrFzVIHYUERzX2FKeEUwTTQ
- the piano* files are both 16-bit
- the bullhorn.aiff is 16-bit
- the mp3 is ... an mp3

About the Google Console: what's weird is that I haven't even included the
"index.html" bit in the authorised JS origins  .... see the screenshot!
So ... I haven't worked that out yet .... bit confused ....

**Comment by ottonascarella** [comment]
Weird stuff the Google Console thing.

Both AIFF files play on Safari; none on Chrome: Aurora has no support for
AIFF...so it depends on browser support.
I cannot play any FLACs either. It seems that aurora is not actually doing
its job.

**Comment by ottonascarella** [comment]
Found a little information about aurora at the jplayer docs:

http://jplayer.org/latest/demo-01-solution-aurora/

It looks like the whole problem might be caused by CORS
I am not sure how we could handle that.

**Comment by danryu** [comment]
No I think we would be seeing CORS errors explicitly ....

And aurora must be working .... well I can see in the JS console/network
that it's loaded when the bullhorn.aiff plays, for example ....

I NEVER EVER EVER use Safari, at the moment I am testing 100% in Chrome.

So Chrome + aurora + 16bit AIFF _does_ work .... sometimes at least ...

**Comment by danryu** [comment]
Aurora doesn't support AIFF?
Sure it does ... that's why I'm using it :)

**Review by danryu — APPROVED** [review]
cheers maychee

**Pull request merged**
